### ISSUE TITLE
Opening incorrect static images in labelme.

### ISSUE THREAD

**Issue by wzkariampuzha** [wzkariampuzha/SurgUI#1]
Whenever a picture is snapped and then opens in labelme, a frame a bit before or after the one you are looking at opens. This is likely a NumPy env issue. Attempted solve 1 month ago with a new conda environment but there were package conflicts. Will attempt a solve with virtualenv.

```
2024-11-01 14:43:25.800 python[29692:1974865] +[IMKInputSession subclass]: chose IMKInputSession_Modern
nottissuesecretion,secretionslens,secretionstissue

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/Users/wzk/opt/anaconda3/envs/SurgUI-venv/bin/labelme", line 5, in <module>
    from labelme.__main__ import main
  File "/Users/wzk/opt/anaconda3/envs/SurgUI-venv/lib/python3.10/site-packages/labelme/__main__.py", line 14, in <module>
    from labelme.app import MainWindow
  File "/Users/wzk/opt/anaconda3/envs/SurgUI-venv/lib/python3.10/site-packages/labelme/app.py", line 21, in <module>
    from labelme.ai import MODELS
  File "/Users/wzk/opt/anaconda3/envs/SurgUI-venv/lib/python3.10/site-packages/labelme/ai/__init__.py", line 3, in <module>
    from .efficient_sam import EfficientSam
  File "/Users/wzk/opt/anaconda3/envs/SurgUI-venv/lib/python3.10/site-packages/labelme/ai/efficient_sam.py", line 6, in <module>
    import onnxruntime
  File "/Users/wzk/opt/anaconda3/envs/SurgUI-venv/lib/python3.10/site-packages/onnxruntime/__init__.py", line 23, in <module>
    from onnxruntime.capi._pybind_state import ExecutionMode  # noqa: F401
  File "/Users/wzk/opt/anaconda3/envs/SurgUI-venv/lib/python3.10/site-packages/onnxruntime/capi/_pybind_state.py", line 32, in <module>
    from .onnxruntime_pybind11_state import *  # noqa
AttributeError: _ARRAY_API not found
ImportError: numpy.core.multiarray failed to import

The above exception was the direct cause of the following exception:

SystemError: <built-in function __import__> returned a result with an exception set
2024-11-01 14:44:21,535 [INFO   ] __init__:get_config:67- Loading config file from: /Users/wzk/.labelmerc
2024-11-01 14:44:22.658 python[29720:1976234] +[IMKClient subclass]: chose IMKClient_Modern
2024-11-01 14:44:22.658 python[29720:1976234] +[IMKInputSession subclass]: chose IMKInputSession_Modern
```

**Comment by wzkariampuzha** [comment]
Update, I was able to create a new environment without the NumPy issues, but still had the problem of incorrect frames being pulled up. 

These are the logs: 
```
[00007f8699e09720] videotoolbox decoder: Using Video Toolbox to decode 'h264'
[00007f8699e09720] videotoolbox decoder: vt cvpx chroma: 420v
[00007f8699e09720] main decoder error: Timestamp conversion failed for 622171467: no reference clock
[00007f8699e09720] main decoder error: Could not convert timestamp 0 for videotoolbox
2024-11-02 03:24:58,534 [INFO   ] __init__:get_config:67- Loading config file from: /Users/wzk/.labelmerc
```

Looking into it more, this seems to be a [known issue with VLC media player](https://forum.videolan.org/viewtopic.php?t=143368) when playing certain video types, and is thus outside of the scope of this project.
